### ISSUE TITLE
Is this repository abandoned ?

### ISSUE THREAD

**Issue by Nek-** [andrelohmann/ansible-role-wkhtmltopdf#2]
Hello, it seems that this repository is not compatible with the new LTS of Ubuntu (22.04 - Jammy). Do you have any plan to fix this?  
Also, it seems that there are no support either in the package used... https://github.com/wkhtmltopdf/packaging/releases

**Comment by nayluge** [comment]
You have to adapt the version with these variable : 

``` 
wkhtmltopdf_full_release: "0.12.6.1-2"
```
